#logging.level.org.springframework: ERROR
logging.level.org.hibernate: ERROR
logging.level.org.xnio: ERROR
logging.level.org.okkam: INFO

spring:
  port: 8081
  application:
    name: stop-backend
  http:
    multipart:
      enabled: false
  profiles:
    active: development

# Profiles
---
spring.profiles: development

server:
  port: 8081

spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    platform: mysql
    testWhileIdle: true
    url: jdbc:h2:file:/tmp/stop-backend;AUTO_SERVER=true
    username: sa
    validationQuery: SELECT 1
  http:
    multipart:
      enabled: false
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  port: 8081

  h2:
    console:
      enabled:true
      path:/h2-console